# Use an official Node.js runtime as a parent image
FROM python

# Set the working directory
WORKDIR /usr/src/app

# Install app dependencies
RUN python -m pip install tink
RUN python -m pip install flask

# Copy the current directory contents into the container
COPY Server2.py .

# Expose the port the app runs on
EXPOSE 3001

# Run the application
CMD ["python", "./Server2.py"]