FROM python

# Set the working directory
WORKDIR /usr/src/app

# Install app dependencies
RUN python -m pip install flask
RUN python -m pip install argon2-cffi
RUN python -m pip install requests

# Copy the current directory contents into the container
COPY Server1.py .

# Expose the port the app runs on
EXPOSE 3001

# Run the application
CMD ["python", "./Server1.py"]